services:
  server:
    build:
      context: .
    ports:
      - 3003:3000
      - 3011:3011
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://schedule-svc:verysecretpassword@db/schedule-service?schema=public
      USER_SERVICE_URL: http://host.docker.internal:3000
      CLASSROOM_SERVICE_URL_GRPC: host.docker.internal:3010
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17
    restart: always
    ports:
      - 5435:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: schedule-svc
      POSTGRES_PASSWORD: verysecretpassword
      POSTGRES_DB: schedule-service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "schedule-service"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  db-data:
